CREATE DATABASE EduSys
GO

USE EduSys
GO

CREATE TABLE ChuyenDe(
	MaCD NCHAR(5) PRIMARY KEY,
	TenCD NVARCHAR(50) NOT NULL,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	Hinh NVARCHAR(50) NOT NULL,
	MoTa NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE NhanVien(
	MaNV NVARCHAR(50) PRIMARY KEY,
	MatKhau VARCHAR(50) NOT NULL,
	HoTen NVARCHAR(50) NOT NULL,
	VaiTro BIT NOT NULL
)
GO

CREATE TABLE NguoiHoc(
	MaNH NCHAR(7) PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh BIT NOT NULL,
	DienThoai NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	GhiChu NVARCHAR(MAX) NULL,
	MaNV NVARCHAR(50) FOREIGN KEY(MaNV) REFERENCES dbo.NhanVien(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
	NgayDK DATE NOT NULL
)
GO

CREATE TABLE KhoaHoc(
	MaKH INT IDENTITY(1,1) PRIMARY KEY,
	MaCD NCHAR(5) FOREIGN KEY(MaCD) REFERENCES dbo.ChuyenDe(MaCD) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	NgayKG DATE NOT NULL,
	GhiChu NVARCHAR(50) NULL,
	MaNV NVARCHAR(50) FOREIGN KEY(MaNV) REFERENCES dbo.NhanVien(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
	NgayTao DATE NOT NULL
)
GO

CREATE TABLE HocVien(
	MaHV INT IDENTITY(1,1) PRIMARY KEY,
	MaKH INT FOREIGN KEY(MaKH) REFERENCES dbo.KhoaHoc(MaKH) ON DELETE NO ACTION ON UPDATE CASCADE NOT NULL,
	MaNH NCHAR(7) FOREIGN KEY(MaNH) REFERENCES dbo.NguoiHoc(MaNH) ON DELETE NO ACTION NOT NULL,
	Diem FLOAT NOT NULL
)
GO

CREATE TRIGGER UpdateMaNH
ON NguoiHoc
AFTER UPDATE
AS
BEGIN
    UPDATE HocVien
    SET MaNH = inserted.MaNH
    FROM HocVien
    INNER JOIN inserted ON HocVien.MaNH = inserted.MaNH
    INNER JOIN deleted ON HocVien.MaNH = deleted.MaNH
END


